# this first section will be written to the config.json 
# subsequent sections are used in the Python config parser
git:
  repository: https://github.com/solidsgroup/alamo.git
  branch: development
system_packages:
  - git
  - build-essential
  - g++
  - gfortran
  - clang
  - libgfortran-14-dev
  - libstdc++-14-dev
  - libopenmpi-dev
  - libeigen3-dev
  - libpng-dev
  - python3
  - ca-certificates
amrex_dir: ext/amrex
base_configure_cmd: ./configure
