git:
  repository: https://github.com/solidsgroup/alamo.git
  branch: development
packages:
  - build-essential
  - g++
  - gfortran
  - clang
  - libgfortran-14-dev
  - libstdc++-14-dev
  - libopenmpi-dev
  - libeigen3-dev
  - libpng-dev
  - git
